const FIELD = 'FIELD';

export const SET_FIELDS = `${FIELD}_SET_FIELDS`;
export const CREATE_FIELD = `${FIELD}_CREATE_FIELD`;
export const DELETE_FIELD = `${FIELD}_DELETE_FIELD`;
export const UPDATE_FIELD = `${FIELD}_UPDATE_FIELD`;
export const SET_CURRENT_FIELD_ID = `${FIELD}_SET_CURRENT_FIELD_ID`;
