const YEAR = 'YEAR';

export const CREATE_YEAR = `${YEAR}_CREATE_YEAR`;
export const SET_YEARS = `${YEAR}_SET_YEARS`;
export const SET_CURRENT_YEAR_ID = `${YEAR}_SET_CURRENT_YEAR_ID`;
export const DELETE_YEAR = `${YEAR}_DELETE_YEAR`;
export const UPDATE_ZONAL_MANAGEMENT_ROW = `${YEAR}_UPDATE_ZONAL_MANAGEMENT_ROW`;
export const GET_ZONAL_MANAGEMENT = `${YEAR}_GET_ZONAL_MANAGEMENT`;
export const SET_NORM_BOT = `${YEAR}_SET_NORM_BOT`;
export const UPDATE_NORM_BOT_ROW = `${YEAR}_UPDATE_NORM_BOT_ROW`;
export const DELETE_NORM_BOT_ROW = `${YEAR}_DELETE_NORM_BOT_ROW`;
export const SET_IMG_YIELD = `${YEAR}_SET_IMG_YIELD`;
export const SET_IMG_CONTROL_AREA = `${YEAR}_SET_IMG_CONTROL_AREA`;
export const SET_DESCRIPTION = `${YEAR}_SET_DESCRIPTION`;
export const SET_FILES = `${YEAR}_SET_FILES`;
export const CREATE_FILES = `${YEAR}_CREATE_FILES`;
export const DELETE_FILE = `${YEAR}_DELETE_FILE`;
export const UPDATE_FILE = `${YEAR}_UPDATE_FILE`;
