const REGION = 'REGION';

export const CREATE_REGION = `${REGION}_CREATE_REGION`;
export const SET_REGIONS = `${REGION}_SET_REGIONS`;
export const DELETE_REGION = `${REGION}_DELETE_REGION`;
export const UPDATE_REGION = `${REGION}_UPDATE_REGION`;
export const SET_CURRENT_REGION_ID = `${REGION}_SET_CURRENT_REGION_ID`;
