const localization = {
    'notFound.subTitle': 'На жаль, відвіданої вами сторінки не існує.',
    'notFound.buttonText': 'На головну',
    'auth.validationLoginRequired': 'Будь ласка введіть свій логін!',
    'auth.validationPasswordRequired': 'Будь ласка введіть свій пароль!',
    'auth.enter': 'Вхід',
    password: 'Пароль',
    login: 'Логін',
    companies: 'Компанії',
    regions: 'Регіони',
    fields: 'Поля',
    edit: 'ред.',
    delete: 'вид.',
    'region.add': 'Додати регіон',
    'region.create': 'Створити регіон',
    'region.name': 'Назва регіона',
    'region.newName': 'Нова назва регіона',
    'region.updateName': 'Оновити назву регіон',
    'region.validationRegionNameRequired': 'Будь ласка введіть назву для регіона!',
    'region.validationNewRegionNameRequired': 'Будь ласка введіть нову назву для регіона!',
    'company.create': 'Створити компанію',
    'company.delete': 'Видалити компанію',
    'company.validationLoginRequired': 'Будь ласка введіть логін для компанії!',
    'company.validationCompanyNameRequired': `Будь ласка введіть назву для компанії!`,
    'company.validationPasswordRequired': 'Будь ласка введіть пароль для компанії!',
    'company.login': 'Логін компанії',
    'company.name': 'Назва',
    'field.add': 'Додати поле',
    'field.name': 'Назва поля',
    'field.create': 'Створити поле',
    'field.updateName': 'Оновити назву поля',
    'field.newName': 'Нова назва поля',
    'field.validationFieldNameRequired': 'Будь ласка введіть назву для поля!',
    'field.validationNewFieldNameRequired': 'Будь ласка введіть нову назву для поля!',
    okModalCreateText: 'Створити',
    okModalSaveText: 'Зберегти',
    okModalDeleteText: 'Видалити',
    cancelText: 'Скасувати'
};

export default localization;
