export const ADD_COMPANY = 'ADD_COMPANY';
export const SET_CURRENT_COMPANY_ID = 'SET_CURRENT_COMPANY_ID';
export const SET_COMPANIES = 'SET_COMPANIES';
export const DELETE_COMPANY = 'DELETE_COMPANY';
