const COMPANY = 'COMPANY';

export const ADD_COMPANY = `${COMPANY}_ADD_COMPANY`;
export const SET_CURRENT_COMPANY_ID = `${COMPANY}_SET_CURRENT_COMPANY_ID`;
export const SET_COMPANIES = `${COMPANY}_SET_COMPANIES`;
export const DELETE_COMPANY = `${COMPANY}_DELETE_COMPANY`;
export const UPDATE_COMPANY = `${COMPANY}_UPDATE_COMPANY`;
export const UPDATE_COMPANY_PASSWORD = `${COMPANY}_UPDATE_COMPANY_PASSWORD`;
export const SET_COMPANY = `${COMPANY}_SET_COMPANY`;
